'use strict';

class ReutersPicturesError extends Error {}
class ReutersPicturesSearchServiceClient_500Error extends ReutersPicturesError {}
class ReutersPicturesSearchServiceClient_UrlTooLongError extends ReutersPicturesError {}
class ReutersPicturesErrorAuthenticationService_AuthenticationFailedError extends ReutersPicturesError {}

module.exports = {
    ReutersPicturesError: ReutersPicturesError,
    ReutersPicturesSearchServiceClient_500Error: ReutersPicturesSearchServiceClient_500Error,
    ReutersPicturesSearchServiceClient_UrlTooLongError: ReutersPicturesSearchServiceClient_UrlTooLongError,
    ReutersPicturesErrorAuthenticationService_AuthenticationFailedError: ReutersPicturesErrorAuthenticationService_AuthenticationFailedError
};